# Global settings applied to the whole site.
#
# “base” is the directory to change to before starting build. If you set base:
#        that is where we will look for package.json/.nvmrc/etc, not repo root!
# “command” is your build command.
# “publish” is the directory to publish (relative to the root of your repo).

[build]
  publish = "dist"

# The `from = "/*"` redirect tells Netlify to redirect
# all pages to the `to = "index.html"` file. Basically, this
# is a 'rewrite' rule, not a 'redirect' one.
# Le `status = 200` is deceiving Netlify into thinking
# that it's a redirect, but it's a rewrite.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
 